### ISSUE TITLE
Domain name does not exist anymore

### ISSUE THREAD

**Issue by AKiuhfsduryzeuryfbgsdh** [melmorabity/tv_grab_fr_telerama#1]
Domain name: guidetv-iphone.telerama.fr does not exist anymore.
Grabber stopped working for me on August 22nd 2017.

**Comment by EMegamanu** [comment]
Same thing, EPG is now empty.

**Comment by ybonnel** [comment]
Same here.

**Comment by melmorabity** [comment]
Fixed in latest version... At last
